// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "3e2596f8-8864-4d2d-a640-24109fd20648";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onTempChange();
void onServoValChange();
void onLed1Change();
void onLed2Change();
void onLed3Change();

float temp;
int servoVal;
bool led1;
bool led2;
bool led3;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);
  ArduinoCloud.addProperty(servoVal, READWRITE, ON_CHANGE, onServoValChange);
  ArduinoCloud.addProperty(led1, READWRITE, ON_CHANGE, onLed1Change);
  ArduinoCloud.addProperty(led2, READWRITE, ON_CHANGE, onLed2Change);
  ArduinoCloud.addProperty(led3, READWRITE, ON_CHANGE, onLed3Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
